# 🧪 Prueba de la librería `algebra-lineal-sheets`

Este notebook verifica que la librería instalada en el entorno `.venv` funciona de punta a punta usando el **modo Excel local** (sin Google ni credenciales):

1. Exporta las matrices `A` y `b` al archivo `mis_matrices.xlsx` (una pestaña por matriz).
2. Lista las pestañas con `workspace()`.
3. Vuelve a importar `A` y `b` desde el Excel.
4. Resuelve el sistema lineal $Ax = b$ y exporta la solución `x`.
5. Comprueba el contenido del archivo generado.

> **Kernel:** selecciona el intérprete de `.venv` (Python 3.12) al ejecutar este notebook en VS Code.

In [1]:
import numpy as np
from algebra_lineal import *

version()

📚 ALGEBRA LINEAL v1.1.0
🎓 Para estudiantes de álgebra lineal
🔧 Ejecuta: configurar() para empezar
📖 Ayuda completa: ayuda()
🔗 PyPI: https://pypi.org/project/algebra-lineal-sheets/
📦 ALGEBRA LINEAL v1.1.0
👨‍🏫 Autor: Francisco Pérez Mogollón
📚 Álgebra lineal simplificada con Google Sheets y Excel
🔗 PyPI: https://pypi.org/project/algebra-lineal-sheets/
🛠️  Instalación: pip install algebra-lineal-sheets


In [2]:
# Modo Excel local: no requiere internet ni cuenta de Google
configurar(sheet='mis_matrices.xlsx')

📊 Modo Excel local: mis_matrices.xlsx
⚠️  El archivo aún no existe: exportar() lo creará
📖 Usa ayuda() para ver todos los comandos disponibles


True

In [3]:
# Crear las matrices del sistema y exportarlas al Excel
A = np.array([[3.0, 1.0],
              [1.0, 2.0]])
b = np.array([[9.0],
              [8.0]])

exportar('A', 'b')

✅ A → creada
✅ b → creada
🎯 ¡Exportadas exitosamente!: A, b
🔗 Revisa tu archivo — 📊 Excel local: mis_matrices.xlsx


['A', 'b']

In [4]:
# Ver las pestañas del archivo y sus dimensiones
workspace()

🏢 WORKSPACE — 📊 Excel local: mis_matrices.xlsx
#   NOMBRE               DIMENSIONES  TIPO           
---------------------------------------------------------------------------
1   A                    2×2          📋 Matriz       
2   b                    2×1          📉 Vector columna
💡 Usa importar('nombre') para traer matrices específicas


{'A': {'tipo': 'matriz', 'dimensiones': (2, 2)},
 'b': {'tipo': 'vector_columna', 'dimensiones': (2, 1)}}

In [5]:
# Borrar las variables del namespace y volver a importarlas desde el Excel
del A, b
importar('A', 'b')

print('A =')
print(A)
print('b =')
print(b)

🔄 Importando desde 📊 Excel local: mis_matrices.xlsx: A, b
✅ A → matriz (2, 2)
✅ b → vector columna (2, 1)

🎯 ¡Listo! Variables disponibles: A, b
A =
[[3. 1.]
 [1. 2.]]
b =
[[9.]
 [8.]]


In [6]:
# Resolver Ax = b, verificar la solución y exportarla
x = np.linalg.solve(A, b)
print('x =')
print(x)

assert np.allclose(A @ x, b), 'La solución no verifica A @ x = b'
print('✅ Verificado: A @ x ≈ b')

exportar('x')

x =
[[2.]
 [3.]]
✅ Verificado: A @ x ≈ b
✅ x → creada
🎯 ¡Exportadas exitosamente!: x
🔗 Revisa tu archivo — 📊 Excel local: mis_matrices.xlsx


['x']

In [7]:
# Comprobar el archivo Excel generado leyéndolo directamente con openpyxl
from pathlib import Path
from openpyxl import load_workbook

ruta = Path('mis_matrices.xlsx')
print('Archivo existe:', ruta.exists())
print('Ubicación:', ruta.resolve())

libro = load_workbook(ruta, data_only=True)
print('Pestañas:', libro.sheetnames)
print('Pestaña x:', [[celda.value for celda in fila] for fila in libro['x'].iter_rows()])

Archivo existe: True
Ubicación: C:\Users\econo\OneDrive\FLACSO\Clases\algebra-lineal-sheets\ejemplos\mis_matrices.xlsx
Pestañas: ['A', 'b', 'x']
Pestaña x: [[2], [3]]
